server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/config_server
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
  profiles:
    include: drl
  
drools:
  drlRules: >
    import com.example.configclient.model.CustomerRequest
    import com.example.configclient.model.CustomerCategory;
    global com.example.configclient.model.CustomerType customerType;
    dialect "mvel"

    rule "Categorize customer based on age"
        when
            CustomerRequest(age < 20)
        then
            customerType.setCustomerType(CustomerCategory.SENIOR_CITIZEN);
    end

    rule "Categorize senior citizen customer based on age"
        when
            CustomerRequest(age > 50)
        then
          customerType.setCustomerType(CustomerCategory.KIDS);
    end

    rule "Categorize customer based on number of orders"
        when
            CustomerRequest(numberOfOrders == 0)
        then
            customerType.setCustomerType(CustomerCategory.SUSPENDED);
    end

    rule "Categorize customer general case"
        when
            CustomerRequest((gender == "M" || gender == "F") && age > 20 && age < 50)
        then
            customerType.setCustomerType(CustomerCategory.GENERAL);
    end
